name: theater
description: Actor model implementation in Dart. This package makes it easier to work with isolates, create clusters of isolates.
version: 0.1.1
repository: https://github.com/GlebBatykov/theater

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  async: ^2.8.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0