name: theater
description: Actor framework for Dart. This package makes it easier to work with isolates, create clusters of isolates.
version: 0.2.11
repository: https://github.com/GlebBatykov/theater

environment:
  sdk: '>=2.15.0 <3.0.0'

# dependencies:

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  async: ^2.8.2