name: theater
description: Actor model implementation in Dart
version: 0.1.0
repository: https://github.com/GlebBatykov/theater

environment:
  sdk: '>=2.14.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  async: ^2.8.2